language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/build/js/node_modules
    - $HOME/build/js/packages_imported
install:
  - $HOME/gradlew assemble
script:
  - $HOME/gradlew jsBrowserDistribution
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build/distributions
  on:
    branch: master